### ISSUE TITLE
Can not get Spotify to play 

### ISSUE THREAD

**Issue by joshdyod** [forslund/mopidy_skill#1]
I installed the skill and ran mopidy, it looks like it runs fine. 
However, I can not get Spotify to run.  I have restarted Mycroft, checked perms and chown, any help on this would rock!

2017-05-08 14:38:54,135 - SpeechClient - INFO - Utterance: [u'play discover weekly']
2017-05-08 14:39:00,326 - mycroft.client.speech.mic - DEBUG - Recording...
2017-05-08 14:39:00,327 - SpeechClient - INFO - Begin Recording...
Playing WAVE '/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.10-py2.7.egg/mycroft/res/snd/start_listening.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
2017-05-08 14:39:03,267 - SpeechClient - INFO - End Recording...

2017-05-08 14:44:31,795 - SpeechClient - INFO - Utterance: [u'search spotify for get lucky']
2017-05-08 14:44:32,190 - mycroft.client.speech.mic - DEBUG - Recording...
2017-05-08 14:44:32,191 - SpeechClient - INFO - Begin Recording...
Playing WAVE '/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.10-py2.7.egg/mycroft/res/snd/start_listening.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo

pi@picroft:~ $ mopidy
INFO     Starting Mopidy 2.1.0
INFO     Loading config from builtin defaults
INFO     Loading config from /home/pi/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: spotify, mpd, http, stream, m3u, softwaremixer, file
INFO     Disabled extensions: local
WARNING  Found local configuration errors, the extension has been automatically disabled:
WARNING    local/media_dir must be set.
WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: SpotifyBackend, StreamBackend, M3UBackend, FileBackend
INFO     Audio output set to "autoaudiosink"
INFO     Starting Mopidy core
INFO     Logged in to Spotify in offline mode
INFO     Logged in to Spotify in online mode
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
ERROR    Frontend (MpdFrontend) initialization error: MPD server startup failed: [Errno 98] Address already in use
ERROR    Frontend (HttpFrontend) initialization error: HTTP server startup failed: [Errno 98] Address already in use
INFO     Starting GLib mainloop

pi@picroft:/opt/mycroft/skills/mopidy_skill $ ls -lha
total 88K
drwxr-xr-x  6 mycroft mycroft 4.0K May  8 14:36 .
drwxrwxrwx 26 mycroft mycroft 4.0K May  8 14:27 ..
drwxr-xr-x  3 mycroft mycroft 4.0K May  8 14:27 dialog
drwxr-xr-x  8 mycroft mycroft 4.0K May  8 14:27 .git
-rw-r--r--  1 mycroft mycroft 6.1K May  8 14:27 __init__.py
-rw-r--r--  1 mycroft mycroft 7.1K May  8 14:36 __init__.pyc
-rw-r--r--  1 mycroft mycroft  35K May  8 14:27 LICENSE.txt
-rw-r--r--  1 mycroft mycroft 6.4K May  8 14:27 mopidypost.py
-rw-r--r--  1 mycroft mycroft 2.3K May  8 14:27 README.md
drwxr-xr-x  3 mycroft mycroft 4.0K May  8 14:27 regex
drwxr-xr-x  3 mycroft mycroft 4.0K May  8 14:27 vocab

pi@picroft:/opt/mycroft/skills $ ls -lha
total 104K
drwxr-xr-x  6 mycroft mycroft 4.0K May  8 14:36 mopidy_skill

**Comment by forslund** [comment]
From the mopidy output it looks like the httpfrontend can't be started
properly. Whitout this the skill can't communicate with mopidy.

Den 8 maj 2017 4:48 em skrev "joshdyod" <notifications@github.com>:

I installed the skill and ran mopidy, it looks like it runs fine.
However, I can not get Spotify to run. I have restarted Mycroft, checked
perms and chown, any help on this would rock!

2017-05-08 14:38:54,135 - SpeechClient - INFO - Utterance: [u'play discover
weekly']
2017-05-08 14:39:00,326 - mycroft.client.speech.mic - DEBUG - Recording...
2017-05-08 14:39:00,327 - SpeechClient - INFO - Begin Recording...
Playing WAVE '/usr/local/lib/python2.7/site-packages/mycroft_core-0.
8.10-py2.7.egg/mycroft/res/snd/start_listening.wav' : Signed 16 bit Little
Endian, Rate 44100 Hz, Stereo
2017-05-08 14:39:03,267 - SpeechClient - INFO - End Recording...

2017-05-08 14:44:31,795 - SpeechClient - INFO - Utterance: [u'search
spotify for get lucky']
2017-05-08 14:44:32,190 - mycroft.client.speech.mic - DEBUG - Recording...
2017-05-08 14:44:32,191 - SpeechClient - INFO - Begin Recording...
Playing WAVE '/usr/local/lib/python2.7/site-packages/mycroft_core-0.
8.10-py2.7.egg/mycroft/res/snd/start_listening.wav' : Signed 16 bit Little
Endian, Rate 44100 Hz, Stereo

pi@picroft:~ $ mopidy
INFO Starting Mopidy 2.1.0
INFO Loading config from builtin defaults
INFO Loading config from /home/pi/.config/mopidy/mopidy.conf
INFO Loading config from command line options
INFO Enabled extensions: spotify, mpd, http, stream, m3u, softwaremixer,
file
INFO Disabled extensions: local
WARNING Found local configuration errors, the extension has been
automatically disabled:
WARNING local/media_dir must be set.
WARNING Please fix the extension configuration errors or disable the
extensions to silence these messages.
INFO Starting Mopidy mixer: SoftwareMixer
INFO Starting Mopidy audio
INFO Starting Mopidy backends: SpotifyBackend, StreamBackend, M3UBackend,
FileBackend
INFO Audio output set to "autoaudiosink"
INFO Starting Mopidy core
INFO Logged in to Spotify in offline mode
INFO Logged in to Spotify in online mode
INFO Starting Mopidy frontends: MpdFrontend, HttpFrontend
ERROR Frontend (MpdFrontend) initialization error: MPD server startup
failed: [Errno 98] Address already in use
ERROR Frontend (HttpFrontend) initialization error: HTTP server startup
failed: [Errno 98] Address already in use
INFO Starting GLib mainloop

pi@picroft:/opt/mycroft/skills/mopidy_skill $ ls -lha
total 88K
drwxr-xr-x 6 mycroft mycroft 4.0K May 8 14:36 .
drwxrwxrwx 26 mycroft mycroft 4.0K May 8 14:27 ..
drwxr-xr-x 3 mycroft mycroft 4.0K May 8 14:27 dialog
drwxr-xr-x 8 mycroft mycroft 4.0K May 8 14:27 .git
-rw-r--r-- 1 mycroft mycroft 6.1K May 8 14:27 *init*.py
-rw-r--r-- 1 mycroft mycroft 7.1K May 8 14:36 *init*.pyc
-rw-r--r-- 1 mycroft mycroft 35K May 8 14:27 LICENSE.txt
-rw-r--r-- 1 mycroft mycroft 6.4K May 8 14:27 mopidypost.py
-rw-r--r-- 1 mycroft mycroft 2.3K May 8 14:27 README.md
drwxr-xr-x 3 mycroft mycroft 4.0K May 8 14:27 regex
drwxr-xr-x 3 mycroft mycroft 4.0K May 8 14:27 vocab

pi@picroft:/opt/mycroft/skills $ ls -lha
total 104K
drwxr-xr-x 6 mycroft mycroft 4.0K May 8 14:36 mopidy_skill

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/forslund/mopidy_skill/issues/1>, or mute the thread

**Comment by forslund** [comment]
Hi I think I need to test this on a picroft image, and I can do that earliest tomorrow. I'm out traveling and for some reason I haven't got my rPi along for the trip =(

**Comment by joshdyod** [comment]
Thank you again for all the help. I am going to try to change the port for mopidy open up access in iptables for it and give that a try too.

**Comment by joshdyod** [comment]
Ran status instead of trying to start mopidy, it looks like it starts on boot. 


pi@picroft:~ $ sudo service mopidy status
? mopidy.service - Mopidy music server
   Loaded: loaded (/lib/systemd/system/mopidy.service; enabled)
   Active: active (running) since Tue 2017-05-09 13:17:05 UTC; 13min ago
  Process: 509 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
  Process: 482 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
 Main PID: 511 (mopidy)
   CGroup: /system.slice/mopidy.service
           +-511 /usr/bin/python /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopi...

May 09 13:17:11 picroft mopidy[511]: INFO     Starting Mopidy audio
May 09 13:17:11 picroft mopidy[511]: INFO     Starting Mopidy backends: StreamBackend, M3UBacke...kend
May 09 13:17:11 picroft mopidy[511]: INFO     Audio output set to "autoaudiosink"
May 09 13:17:11 picroft mopidy[511]: INFO     No local library metadata cache found at /var/lib...age.
May 09 13:17:11 picroft mopidy[511]: INFO     Loaded 0 local tracks using json
May 09 13:17:12 picroft mopidy[511]: INFO     Starting Mopidy core
May 09 13:17:12 picroft mopidy[511]: INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
May 09 13:17:12 picroft mopidy[511]: INFO     MPD server running at [::ffff:127.0.0.1]:6600
May 09 13:17:12 picroft mopidy[511]: INFO     HTTP server running at [::ffff:127.0.0.1]:6680
May 09 13:17:12 picroft mopidy[511]: INFO     Starting GLib mainloop
Hint: Some lines were ellipsized, use -l to show in full.


However, issue still persists.

**Comment by forslund** [comment]
Then it's something with the skill. I pushed my most recent changes to github this morning, I might have missed a crucial update in the repo.

I tested setting it up from scratch on my Laptop this morning and it worked fine but there might be something on the Pi that I haven't thought of.
 Can you send me the skill log from mycroft? It might be in `/var/log/mycroft`

Hopefully I'll get time to setup the rPi with the latest Picroft image tonight or tomorrow morning.

Note the Discover weekly list can be missing due to changes on spotify if the mopidy-spotify isn't the absolutely latest, My goto test phrase has been `search spotify for hello nasty` which I know give me the desired output. Since this morning failure to find anything will be reported with a voice message so you'll know a search has been performed.

Thanks for reporting this, I'll do my best to help you with a fix

**Comment by joshdyod** [comment]
I am getting a can not find album message now after installing your most recent update. But it just doesn't play anything. I tried "search Spotify for hello nasty" but it came back wih an error saying "could not find album  hello nasty"


Line 221: 2017-05-09 16:44:42,893 - Skills - DEBUG - {"type": "register_vocab", "data": {"start": "mopidy", "end": "Application"}, "context": null}
	Line 378: 2017-05-09 16:44:49,133 - mycroft.skills.core - INFO - ATTEMPTING TO LOAD SKILL: mopidy_skill
	Line 379: 2017-05-09 16:44:49,209 - mopidy_skill - INFO - initializing Mopidy skill
	Line 379: 2017-05-09 16:44:49,209 - mopidy_skill - INFO - initializing Mopidy skill
	Line 381: 2017-05-09 16:44:49,212 - media - INFO - loading vocab files from /opt/mycroft/skills/mopidy_skill/vocab/en-us
	Line 384: 2017-05-09 16:44:49,255 - mycroft.skills.core - INFO - Loaded mopidy_skill
	Line 388: 2017-05-09 16:44:49,290 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [], "requires": [["NextKeyword", "NextKeyword"]], "optional": [], "name": "Mopidy Skill:NextIntent"}, "context": null}
	Line 389: 2017-05-09 16:44:49,298 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [], "requires": [["PrevKeyword", "PrevKeyword"]], "optional": [], "name": "Mopidy Skill:PrevIntent"}, "context": null}
	Line 390: 2017-05-09 16:44:49,303 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [], "requires": [["PauseKeyword", "PauseKeyword"]], "optional": [], "name": "Mopidy Skill:PauseIntent"}, "context": null}
	Line 391: 2017-05-09 16:44:49,313 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [["PlayKeyword", "ResumeKeyword"]], "requires": [], "optional": [], "name": "Mopidy Skill:PlayIntent"}, "context": null}
	Line 392: 2017-05-09 16:44:49,318 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [], "requires": [["CurrentlyPlayingKeyword", "CurrentlyPlayingKeyword"]], "optional": [], "name": "Mopidy Skill:CurrentlyPlayingIntent"}, "context": null}
	Line 397: 2017-05-09 16:44:49,367 - Skills - DEBUG - {"type": "Mopidy Skill.connect", "data": {}, "context": null}
	Line 398: 2017-05-09 16:44:49,369 - mopidy_skill - INFO - maybe restoring volume
	Line 418: 2017-05-09 16:44:50,029 - requests.packages.urllib3.connectionpool - DEBUG - http://localhost:6680 "POST /mopidy/rpc HTTP/1.1" 200 43
	Line 419: 2017-05-09 16:44:50,039 - mopidy_skill - INFO - Connected to mopidy server
	Line 419: 2017-05-09 16:44:50,039 - mopidy_skill - INFO - Connected to mopidy server
	Line 420: 2017-05-09 16:44:50,040 - mopidy_skill - INFO - Loading content
	Line 422: 2017-05-09 16:44:50,073 - requests.packages.urllib3.connectionpool - DEBUG - http://localhost:6680 "POST /mopidy/rpc HTTP/1.1" 200 41
	Line 424: 2017-05-09 16:44:50,121 - requests.packages.urllib3.connectionpool - DEBUG - http://localhost:6680 "POST /mopidy/rpc HTTP/1.1" 200 41
	Line 426: 2017-05-09 16:44:50,164 - requests.packages.urllib3.connectionpool - DEBUG - http://localhost:6680 "POST /mopidy/rpc HTTP/1.1" 200 41
	Line 428: 2017-05-09 16:44:50,229 - requests.packages.urllib3.connectionpool - DEBUG - http://localhost:6680 "POST /mopidy/rpc HTTP/1.1" 200 41
	Line 430: 2017-05-09 16:44:50,276 - requests.packages.urllib3.connectionpool - DEBUG - http://localhost:6680 "POST /mopidy/rpc HTTP/1.1" 200 41
	Line 432: 2017-05-09 16:44:50,332 - requests.packages.urllib3.connectionpool - DEBUG - http://localhost:6680 "POST /mopidy/rpc HTTP/1.1" 200 41
	Line 434: 2017-05-09 16:44:50,385 - requests.packages.urllib3.connectionpool - DEBUG - http://localhost:6680 "POST /mopidy/rpc HTTP/1.1" 200 41
	Line 436: 2017-05-09 16:44:50,431 - requests.packages.urllib3.connectionpool - DEBUG - http://localhost:6680 "POST /mopidy/rpc HTTP/1.1" 200 41
	Line 437: 2017-05-09 16:44:50,440 - mopidy_skill - INFO - local
	Line 438: 2017-05-09 16:44:50,441 - mopidy_skill - INFO - local
	Line 439: 2017-05-09 16:44:50,442 - mopidy_skill - INFO - local
	Line 440: 2017-05-09 16:44:50,443 - mopidy_skill - INFO - local
	Line 441: 2017-05-09 16:44:50,443 - mopidy_skill - INFO - gmusic
	Line 442: 2017-05-09 16:44:50,444 - mopidy_skill - INFO - gmusic
	Line 443: 2017-05-09 16:44:50,445 - mopidy_skill - INFO - gmusic
	Line 444: 2017-05-09 16:44:50,446 - mopidy_skill - INFO - gmusic
	Line 445: 2017-05-09 16:44:50,447 - mopidy_skill - INFO - spotify
	Line 446: 2017-05-09 16:44:50,447 - mopidy_skill - INFO - spotify
	Line 447: 2017-05-09 16:44:50,448 - mopidy_skill - INFO - spotify
	Line 448: 2017-05-09 16:44:50,449 - mopidy_skill - INFO - spotify
	Line 449: 2017-05-09 16:44:50,460 - Skills - DEBUG - {"type": "register_vocab", "data": {"start": "Mopidy Skill", "end": "NameKeyword"}, "context": null}
	Line 450: 2017-05-09 16:44:50,470 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [], "requires": [["PlayKeyword", "PlayKeyword"], ["PlaylistKeywordMopidy Skill", "PlaylistKeywordMopidy Skill"]], "optional": [], "name": "Mopidy Skill:PlayPlaylistIntentMopidy Skill"}, "context": null}
	Line 450: 2017-05-09 16:44:50,470 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [], "requires": [["PlayKeyword", "PlayKeyword"], ["PlaylistKeywordMopidy Skill", "PlaylistKeywordMopidy Skill"]], "optional": [], "name": "Mopidy Skill:PlayPlaylistIntentMopidy Skill"}, "context": null}
	Line 450: 2017-05-09 16:44:50,470 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [], "requires": [["PlayKeyword", "PlayKeyword"], ["PlaylistKeywordMopidy Skill", "PlaylistKeywordMopidy Skill"]], "optional": [], "name": "Mopidy Skill:PlayPlaylistIntentMopidy Skill"}, "context": null}
	Line 450: 2017-05-09 16:44:50,470 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [], "requires": [["PlayKeyword", "PlayKeyword"], ["PlaylistKeywordMopidy Skill", "PlaylistKeywordMopidy Skill"]], "optional": [], "name": "Mopidy Skill:PlayPlaylistIntentMopidy Skill"}, "context": null}
	Line 451: 2017-05-09 16:44:50,478 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [], "requires": [["PlayKeyword", "PlayKeyword"], ["PlaylistKeyword", "PlaylistKeyword"], ["NameKeyword", "NameKeyword"]], "optional": [], "name": "Mopidy Skill:PlayFromIntentMopidy Skill"}, "context": null}
	Line 451: 2017-05-09 16:44:50,478 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [], "requires": [["PlayKeyword", "PlayKeyword"], ["PlaylistKeyword", "PlaylistKeyword"], ["NameKeyword", "NameKeyword"]], "optional": [], "name": "Mopidy Skill:PlayFromIntentMopidy Skill"}, "context": null}
	Line 452: 2017-05-09 16:44:50,509 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [], "requires": [["SearchKeyword", "SearchKeyword"], ["Source", "Source"], ["SpotifyKeyword", "SpotifyKeyword"]], "optional": [], "name": "Mopidy Skill:SearchSpotifyIntentMopidy Skill"}, "context": null}
	Line 452: 2017-05-09 16:44:50,509 - Skills - DEBUG - {"type": "register_intent", "data": {"at_least_one": [], "requires": [["SearchKeyword", "SearchKeyword"], ["Source", "Source"], ["SpotifyKeyword", "SpotifyKeyword"]], "optional": [], "name": "Mopidy Skill:SearchSpotifyIntentMopidy Skill"}, "context": null}
	Line 453: 2017-05-09 16:44:51,373 - mopidy_skill - INFO - restoring volume
	Line 464: 2017-05-09 16:45:43,185 - Skills - DEBUG - {"type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "data": {"confidence": 0.8333333333333334, "target": null, "intent_type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "SearchKeyword": "search", "Source": "get lucky", "utterance": "search spotify for get lucky", "SpotifyKeyword": "Spotify"}, "context": {"target": null}}
	Line 464: 2017-05-09 16:45:43,185 - Skills - DEBUG - {"type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "data": {"confidence": 0.8333333333333334, "target": null, "intent_type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "SearchKeyword": "search", "Source": "get lucky", "utterance": "search spotify for get lucky", "SpotifyKeyword": "Spotify"}, "context": {"target": null}}
	Line 464: 2017-05-09 16:45:43,185 - Skills - DEBUG - {"type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "data": {"confidence": 0.8333333333333334, "target": null, "intent_type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "SearchKeyword": "search", "Source": "get lucky", "utterance": "search spotify for get lucky", "SpotifyKeyword": "Spotify"}, "context": {"target": null}}
	Line 464: 2017-05-09 16:45:43,185 - Skills - DEBUG - {"type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "data": {"confidence": 0.8333333333333334, "target": null, "intent_type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "SearchKeyword": "search", "Source": "get lucky", "utterance": "search spotify for get lucky", "SpotifyKeyword": "Spotify"}, "context": {"target": null}}
	Line 465: 2017-05-09 16:45:43,187 - mopidy_skill - INFO - Search Spotify Intent
	Line 466: 2017-05-09 16:45:43,188 - mopidy_skill - INFO - {u'confidence': 0.8333333333333334, u'target': None, u'intent_type': u'Mopidy Skill:SearchSpotifyIntentMopidy Skill', u'SearchKeyword': u'search', u'Source': u'get lucky', u'utterance': u'search spotify for get lucky', u'SpotifyKeyword': u'Spotify'}
	Line 466: 2017-05-09 16:45:43,188 - mopidy_skill - INFO - {u'confidence': 0.8333333333333334, u'target': None, u'intent_type': u'Mopidy Skill:SearchSpotifyIntentMopidy Skill', u'SearchKeyword': u'search', u'Source': u'get lucky', u'utterance': u'search spotify for get lucky', u'SpotifyKeyword': u'Spotify'}
	Line 466: 2017-05-09 16:45:43,188 - mopidy_skill - INFO - {u'confidence': 0.8333333333333334, u'target': None, u'intent_type': u'Mopidy Skill:SearchSpotifyIntentMopidy Skill', u'SearchKeyword': u'search', u'Source': u'get lucky', u'utterance': u'search spotify for get lucky', u'SpotifyKeyword': u'Spotify'}
	Line 467: 2017-05-09 16:45:43,189 - mopidy_skill - INFO - get lucky
	Line 469: 2017-05-09 16:45:43,256 - requests.packages.urllib3.connectionpool - DEBUG - http://localhost:6680 "POST /mopidy/rpc HTTP/1.1" 200 93
	Line 470: 2017-05-09 16:45:43,265 - mopidy_skill - INFO - []
	Line 473: 2017-05-09 16:45:43,288 - mopidy_skill - INFO - lowering volume
	Line 476: 2017-05-09 16:45:49,332 - mopidy_skill - INFO - maybe restoring volume
	Line 477: 2017-05-09 16:45:51,336 - mopidy_skill - INFO - restoring volume
	Line 482: 2017-05-09 16:46:34,432 - Skills - DEBUG - {"type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "data": {"confidence": 0.8333333333333334, "target": null, "intent_type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "SearchKeyword": "search", "Source": "random access memories", "utterance": "search spotify for random access memories", "SpotifyKeyword": "Spotify"}, "context": {"target": null}}
	Line 482: 2017-05-09 16:46:34,432 - Skills - DEBUG - {"type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "data": {"confidence": 0.8333333333333334, "target": null, "intent_type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "SearchKeyword": "search", "Source": "random access memories", "utterance": "search spotify for random access memories", "SpotifyKeyword": "Spotify"}, "context": {"target": null}}
	Line 482: 2017-05-09 16:46:34,432 - Skills - DEBUG - {"type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "data": {"confidence": 0.8333333333333334, "target": null, "intent_type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "SearchKeyword": "search", "Source": "random access memories", "utterance": "search spotify for random access memories", "SpotifyKeyword": "Spotify"}, "context": {"target": null}}
	Line 482: 2017-05-09 16:46:34,432 - Skills - DEBUG - {"type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "data": {"confidence": 0.8333333333333334, "target": null, "intent_type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "SearchKeyword": "search", "Source": "random access memories", "utterance": "search spotify for random access memories", "SpotifyKeyword": "Spotify"}, "context": {"target": null}}
	Line 483: 2017-05-09 16:46:34,435 - mopidy_skill - INFO - Search Spotify Intent
	Line 484: 2017-05-09 16:46:34,436 - mopidy_skill - INFO - {u'confidence': 0.8333333333333334, u'target': None, u'intent_type': u'Mopidy Skill:SearchSpotifyIntentMopidy Skill', u'SearchKeyword': u'search', u'Source': u'random access memories', u'utterance': u'search spotify for random access memories', u'SpotifyKeyword': u'Spotify'}
	Line 484: 2017-05-09 16:46:34,436 - mopidy_skill - INFO - {u'confidence': 0.8333333333333334, u'target': None, u'intent_type': u'Mopidy Skill:SearchSpotifyIntentMopidy Skill', u'SearchKeyword': u'search', u'Source': u'random access memories', u'utterance': u'search spotify for random access memories', u'SpotifyKeyword': u'Spotify'}
	Line 484: 2017-05-09 16:46:34,436 - mopidy_skill - INFO - {u'confidence': 0.8333333333333334, u'target': None, u'intent_type': u'Mopidy Skill:SearchSpotifyIntentMopidy Skill', u'SearchKeyword': u'search', u'Source': u'random access memories', u'utterance': u'search spotify for random access memories', u'SpotifyKeyword': u'Spotify'}
	Line 485: 2017-05-09 16:46:34,437 - mopidy_skill - INFO - random access memories
	Line 487: 2017-05-09 16:46:34,480 - requests.packages.urllib3.connectionpool - DEBUG - http://localhost:6680 "POST /mopidy/rpc HTTP/1.1" 200 93
	Line 488: 2017-05-09 16:46:34,489 - mopidy_skill - INFO - []
	Line 491: 2017-05-09 16:46:34,570 - mopidy_skill - INFO - lowering volume
	Line 493: 2017-05-09 16:46:42,160 - mopidy_skill - INFO - maybe restoring volume
	Line 498: 2017-05-09 16:46:44,163 - mopidy_skill - INFO - restoring volume
	Line 515: 2017-05-09 16:47:24,148 - Skills - DEBUG - {"type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "data": {"confidence": 0.8333333333333334, "target": null, "intent_type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "SearchKeyword": "search", "Source": "hello nasty", "utterance": "search spotify for hello nasty", "SpotifyKeyword": "Spotify"}, "context": {"target": null}}
	Line 515: 2017-05-09 16:47:24,148 - Skills - DEBUG - {"type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "data": {"confidence": 0.8333333333333334, "target": null, "intent_type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "SearchKeyword": "search", "Source": "hello nasty", "utterance": "search spotify for hello nasty", "SpotifyKeyword": "Spotify"}, "context": {"target": null}}
	Line 515: 2017-05-09 16:47:24,148 - Skills - DEBUG - {"type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "data": {"confidence": 0.8333333333333334, "target": null, "intent_type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "SearchKeyword": "search", "Source": "hello nasty", "utterance": "search spotify for hello nasty", "SpotifyKeyword": "Spotify"}, "context": {"target": null}}
	Line 515: 2017-05-09 16:47:24,148 - Skills - DEBUG - {"type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "data": {"confidence": 0.8333333333333334, "target": null, "intent_type": "Mopidy Skill:SearchSpotifyIntentMopidy Skill", "SearchKeyword": "search", "Source": "hello nasty", "utterance": "search spotify for hello nasty", "SpotifyKeyword": "Spotify"}, "context": {"target": null}}
	Line 516: 2017-05-09 16:47:24,151 - mopidy_skill - INFO - Search Spotify Intent
	Line 517: 2017-05-09 16:47:24,152 - mopidy_skill - INFO - {u'confidence': 0.8333333333333334, u'target': None, u'intent_type': u'Mopidy Skill:SearchSpotifyIntentMopidy Skill', u'SearchKeyword': u'search', u'Source': u'hello nasty', u'utterance': u'search spotify for hello nasty', u'SpotifyKeyword': u'Spotify'}
	Line 517: 2017-05-09 16:47:24,152 - mopidy_skill - INFO - {u'confidence': 0.8333333333333334, u'target': None, u'intent_type': u'Mopidy Skill:SearchSpotifyIntentMopidy Skill', u'SearchKeyword': u'search', u'Source': u'hello nasty', u'utterance': u'search spotify for hello nasty', u'SpotifyKeyword': u'Spotify'}
	Line 517: 2017-05-09 16:47:24,152 - mopidy_skill - INFO - {u'confidence': 0.8333333333333334, u'target': None, u'intent_type': u'Mopidy Skill:SearchSpotifyIntentMopidy Skill', u'SearchKeyword': u'search', u'Source': u'hello nasty', u'utterance': u'search spotify for hello nasty', u'SpotifyKeyword': u'Spotify'}
	Line 518: 2017-05-09 16:47:24,153 - mopidy_skill - INFO - hello nasty
	Line 520: 2017-05-09 16:47:24,188 - requests.packages.urllib3.connectionpool - DEBUG - http://localhost:6680 "POST /mopidy/rpc HTTP/1.1" 200 93
	Line 521: 2017-05-09 16:47:24,197 - mopidy_skill - INFO - []
	Line 524: 2017-05-09 16:47:24,249 - mopidy_skill - INFO - lowering volume
	Line 527: 2017-05-09 16:47:30,271 - mopidy_skill - INFO - maybe restoring volume
	Line 528: 2017-05-09 16:47:32,275 - mopidy_skill - INFO - restoring volume

**Comment by forslund** [comment]
One question, since you're running an mopidy instance using a system service, have you added your spotify credentials in `/etc/mopidy/mopidy.conf`?

**Comment by joshdyod** [comment]
Yes

**Comment by forslund** [comment]
I'm installing everything needed on my rPi now but compiling the parts for mycroft will take some hours. Will report back tomorrow.

**Comment by joshdyod** [comment]
Thank you again for all your help on this.

**Comment by forslund** [comment]
Hmm. As you say, it looks as if the skill starts ok. But somehow it's not getting any response when searching spotify...

I'm reinstalling mycroft on raspberry Pi. It's building mimic so it will take a while. I'll get back to you when I have some info or more questions.

**Comment by joshdyod** [comment]
Perhaps permissions issue with my mopidy,conf file? I will have to check later. I do have a Spotify Premium account. I have heard that it is necessary for mopidy-spotify.

**Comment by joshdyod** [comment]
Good news! it works! I double checked the /etc/mopidy/mopidy.conf and I needed to add the spotify info.
One last thing. I can say "Search spotify for hello nasty" and it will play, But when I say play X playlist nothing happens. What is the proper phrase for playlists?
I see all my playlist listed in the log file.

I also cant seem to figure out how to pause and restart songs or switch to the next track when using spotify.

**Comment by forslund** [comment]
Great to hear. The vocabulary files wasn't added, they were in my local copy I hadn't added them properly to git. if you update `pause`, `play playlist` `previous track` `next track` should work.

**Comment by forslund** [comment]
A question in return, I can play my playlists and and if I ask `what are we listening to` I get the correct track info. However I get no sound in my headphones. Are you using the 3.5 mm jack or are you using the HDMI output? have you managed to switch between them?

**Comment by joshdyod** [comment]
I will definitely let you know once I get home from work tonight  =D

**Comment by joshdyod** [comment]
Using an audio jack with a power speaker and it works awesomely.  
I did, however, run into some problems with the new additions. pause, previous track, next track still do not work and what is currently playing seems to always return with "Sorry, I don't know what currently playing is". However, the "play playlist" works great, . Thank you for all your time and effort, the work you are doing on this is awesome!

**Comment by forslund** [comment]
Baby steps =) but at least in the right direction.

"Sorry, I don't know what currently playing is" is the fall back skill triggering wolfram alpha without success. So none of the commands seem to work. The keywords seem to be in the repo at least, can you check and report the contents of `/opt/mycroft/skills/mopidy_skill/vocab/en-us/`

Thanks for reporting these issues and sticking with the skill despite a rough start =)

My own problems seem to be the opposite, the commands all work and shows me that music is playing but I can't hear it. I will check with a HDMI cable tonight if sound is sent that way.

**Comment by joshdyod** [comment]
A second restart of pi and it works. The only issue I am having is Pause keeps thinking I say "paws"  unless I say pause music or track, but the skill then doesn't register that.

**Comment by forslund** [comment]
Good to hear! In other news I've managed to get sound from my mopidy instance.

Pause is tricky with the latest STT, it really doesn't want to detect it. When I speak, it almost always thinks I'm saying `post`... `please post the current track` `post track`. Not much I can do about that except adding a couple of synonyms for pause. Maybe `post music` and `paws`... Do you have any other words that it seems to detect instead of pause?

I now lower the volume of the music after wake word is received which makes it easier to give instructions to mycroft.

**Comment by forslund** [comment]
Are you ok with closing this issue or are there more problems that you want fixed before you're happy with the spotify functionality?

**Comment by joshdyod** [comment]
Sorry for the late reply. I was on a camping trip for the last few days, thank you for all your help on this. I would say its fixed. 

If you could add Paws and post music that would be awesome.
