### ISSUE TITLE
Not functioning

### ISSUE THREAD

**Issue by NathanLKing** [forslund/mopidy_skill#15]
Howdy!

Thanks for creating the skill. I'm very keen to use it, but Mycroft isn't "hearing" the requests.

I also can not find the file "~/.mycroft/mycroft.ini" to put this: 
  "Mopidy Skill": {
    "mopidy_url": "http://localhost:6680"
  }

Any assistance would be awesome.

Thanks @forslund

**Comment by forslund** [comment]
Hi, the docs are somewhat outdated. The file path should be `~/.mycroft/mycroft.conf` and the file doesn't exist by default. But you'll only need it if you're running mopidy on a different machine or a different port.

Can you tell me a bit about your setup. Platform and if you're running mopidy on a different device and such.

**Comment by NathanLKing** [comment]
Thanks  @forslund 

Sorry for the delay in responding, lots going on.

I'm running a raspberry pi 3 b+. I've only a standard usb mouse and keyboard attached. I'm using a respeaker 4 mic array by seeed. 

mopidy is on the same device and seemingly starts ok

I'm happy to provide any logs or info that you require. Please keep in mind that I'm new to mycroft and pi.

Perhaps it is clashing with the other audio playing service AVmusic? 

Thanks again.

Nathan

**Comment by astrowave** [comment]
This was probably due to Mopidy dropping the connection due to missing request headers and can likely be closed.

Mopidy seemed to require the header since at least April 2018

https://github.com/mopidy/mopidy/pull/1668/commits/94ba9b6642f4836edaa33df53f6d482110329ad6

**Comment by forslund** [comment]
The skill has been updated significantly since this Issue was posted making it easier to configure. I'm closing it for now. If you still have problems feel free to reopen.
