### ISSUE TITLE
Mycroft does not recognize play commands

### ISSUE THREAD

**Issue by Colonial-Dev** [forslund/mopidy_skill#19]
- Mopidy has been successfully started as a service with a scanned library.

- mopidy_skill has been cloned into ~/.mycroft/skills

- Mopidy is running on the same machine (Pi 3) so I haven't changed ~/.mycroft/mycroft.conf

Asking Mycroft to play "Launch by Logan Gabriel" or some other song/album/etc fails with:

> Just one moment while I look for that...
I'm not sure how to play Launch by Logan Gabriel.

Is there some step I'm missing to make Mycroft use the new skill? Or have I messed up somewhere else?

Thanks.

**Comment by forslund** [comment]
Hi, Mycroft's default skill dir is /opt/mycroft/skills could that be the issue?

It sounds like the common play framework is invoked, I am in the process of moving over to that framework (see the branch common-play), however the handling is still very rough. For a good result you need to be very minimalistic in your utterances: just "play ALBUM" or "play ARTIST"

**Comment by Colonial-Dev** [comment]
Okay, moving the skill to /opt/mycroft/skills fixed the issue, and I'm able to play albums and artists. Thanks for your help.
