### ISSUE TITLE
Mopidy returns error 405 not allowed

### ISSUE THREAD

**Issue by astrowave** [forslund/mopidy_skill#20]
This skill is no longer working because post requests are being dropped by Mopidy.  This is because Mopidy is not receiving the expected header in the request.

Replacing your requests lines from:

`r = requests.post(self.url, data=json.dumps(d))`

to:

`r = requests.post(self.url, headers={"content-type":"application/json"}, data=json.dumps(d))`

Fixes this issue and gets the skill running.

**Comment by forslund** [comment]
Resolved by #21.
