### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by ProjectMoon** [forslund/mopidy_skill#25]
When installing, no requirements.txt is specified. This skill depends on the `fuzzywuzzy` module, which has to be installed manually.

**Comment by forslund** [comment]
Thanks for reporting, I added it to the cps-update branch.

**Comment by ProjectMoon** [comment]
Here is another dependency for you to add: `python-Levenshtein`

If this isn't installed, fuzzywuzzy emits a warning about falling back to a very slow pure Python implementation, which takes around 8-10 seconds per request to find a match. This is, of course, far beyond the [magic 5 second search timeout of mycroft-core](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/common_play_skill.py#L73). Installing `python-Levenshtein` makes the search return a match almost instantly.

Without this dependency, the skill basically doesn't work because it takes too long to find matches.

**Comment by ProjectMoon** [comment]
Of course, this introduces some other issues, e.g. "Play Backdrifts by Radiohead" returns some interesting results (certainly not the actual song Backdrifts).

**Comment by forslund** [comment]
Ow that's a long time to fuzzymatch, you have a larger library than me :) I've updated the PR to include python-Levenshtein as well

As for the second issue with **play x by/with y** I plan to port over some of the parsing from the spotify skill handling this kind of thing after the basic artist/track/album extractions are in and works ok.
