### ISSUE TITLE
~/.mycroft/mycroft.ini no longer exists, what would be json instead

### ISSUE THREAD

**Issue by shyamalpaneri** [forslund/mopidy_skill#4]
Hi,

I am installing this skill on Picroft, Mycroft on RPIE 3 B.

I was trying to install this skill, but couldn't find the mycroft.ini. I checked on the support documentation and found the following.

https://docs.mycroft.ai/release-notes

Major configuration format refactor. The flat mycroft.ini file has now been replaced by a json implementation in mycroft.conf. This should allow for simpler usage and will be much more powerful.
The identity.json has been renamed to identity2.json, to avoid conflicts with the Cerberus account management system.
Configuration loading changes: home.mycroft.ai will periodically be polled poll for changes and no longer requires a complete restart for settings changes to take effect.

Is there a JSON script that we can add to get this skill working or do we have any other alternative?

Also if I have to add a JSON script, should I add it to mycroft.conf

**Comment by forslund** [comment]
Hi thanks for reporting this. I'm currently traveling and I'm typing this on my phone without any way of testing.

You should add the json config for this skill to the mycroft.conf that exists in /etc/mycroft on your picroft image.
```json
  "Mopidy Skill": {
    "mopidy_url": " http://MyMopidyIp:Port"
  }
```

This should be within the outermost {} and if there's other configuration options make sure to add a `,` on the line before above block.

Also note that if mopidy is running on the same machine as mycroft the config isn't needed. Default is localhost

**Comment by shyamalpaneri** [comment]
@forslund Thanks for the instructions, I haven't implemented it yet. Tied up with my office project. Once I try, will update with the status.

**Comment by forslund** [comment]
After a long time the readme has been updated :) Closing this issue.
